/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-09-27 14:07:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.mysql.*;
import java.sql.*;

public final class options_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.mysql");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\"><html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <title>BestMovieTicket</title>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js\"></script>\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600' rel='stylesheet' type='text/css'>\n");
      out.write("  <link href=\"//netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.css\" rel=\"stylesheet\">\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-inverse\">\n");
      out.write("  <div class=\"container\">\n");
      out.write("    <div class=\"navbar-header\">\n");
      out.write("      <a class=\"navbar-brand\" href=\"user.jsp\" style=\"font-size: 40px;\"><b>BestMovieTicket</b></a>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<center>\n");
      out.write("\t<div style=\"float: left; margin-left: 350px;\">\n");
      out.write("\t\t<div class=\"testbox1\">\n");
      out.write("\t\t  <h1>Add Movie</h1>\n");
      out.write("\t\t  <form action=\"userinput\" method=\"POST\">\n");
      out.write("\t\t  <input type=\"text\" name=\"movieName\" placeholder=\"Movie Name\" required/>\n");
      out.write("\t\t  <input type=\"text\" name=\"genere\" placeholder=\"Genere\" required/>\n");
      out.write("\t\t  <input type=\"text\" name=\"duration\" placeholder=\"Duration\" required/>\n");
      out.write("\t\t  <input type=\"text\" name=\"director\" placeholder=\"Direction\" required/>\n");
      out.write("\t\t  <br />\n");
      out.write("\t\t  <br />\n");
      out.write("\t\t   <input class=\"btn btn-primary\" type=\"submit\" value=\"ADD\" >\n");
      out.write("\t\t  </form>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div style=\"float: right; margin-right: 350px;\">\n");
      out.write("\t\t<div style=\"float: left; margin-right: 150px;\">\n");
      out.write("\t\t\t<div class=\"testbox2\">\n");
      out.write("\t\t\t  <h1>Schedule Movie</h1>\n");
      out.write("\t\t\t  <form action=\"schedule\" method=\"POST\">\n");
      out.write("\t\t\t  <input type=\"text\" name=\"movieId\" placeholder=\"Movie ID\">\n");
      out.write("\t          <input type=\"text\" name=\"screen\" placeholder=\"Screen No.\">\n");
      out.write("\t          <input type=\"text\" name=\"slot\" placeholder=\"Slot No.\">\n");
      out.write("\t          <br />\n");
      out.write("\t          <br />\n");
      out.write("\t\t\t   <input class=\"btn btn-primary\" type=\"submit\" value=\"SCHEDULE\">\n");
      out.write("\t\t\t  </form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div style=\"float: right;\">\n");
      out.write("\t\t\t<div class=\"testbox3\">\n");
      out.write("\t\t\t  <h1>Delete Movie</h1>\n");
      out.write("\t\t\t  <form action=\"delete\" method=\"POST\">\n");
      out.write("\t        \t<input type=\"text\" name=\"movieName\" placeholder=\"Movie Name\">\n");
      out.write("\t        \t<br />\n");
      out.write("\t        \t<br />\n");
      out.write("\t\t\t    <input class=\"btn btn-primary\" type=\"submit\" value=\"DELETE\">\n");
      out.write("\t\t\t  </form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</center>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div>\n");
      out.write("    <div class=\"container\">\n");
      out.write("    <br />\n");
      out.write("\t        \t<br />\n");
      out.write("\t    <table class=\"table table-hover\" style=\"margin-top: 350px;\">\n");
      out.write("\t        <thead>\n");
      out.write("\t            <tr>\n");
      out.write("\t            \t<th><b>ID</b></th>\n");
      out.write("\t                <th><b>Title</b></th>\n");
      out.write("\t                <th><b>Genere</b></th>\n");
      out.write("\t            </tr>\n");
      out.write("\t        </thead>\n");
      out.write("\t        <tbody>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t            ");

	                Class.forName("com.mysql.jdbc.Driver");
	                Connection conn = null;
	                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/movie-ticket?serverTimezone=UTC", "root", "linda12345");
	                Statement stmt = null;
	                stmt = conn.createStatement();
	                String query = "select * from moviedatabase";
	                ResultSet rs = null;
	                rs = stmt.executeQuery(query);
	                while(rs.next()){
	            
      out.write("\n");
      out.write("\t            <tr>\n");
      out.write("\t                ");

	                	int id = rs.getInt("id");
	                    String title = rs.getString("title");
	                    String genere = rs.getString("genere");
	                
	                
      out.write("\n");
      out.write("\t                <td>");
      out.print(id );
      out.write("</td>\n");
      out.write("\t                <td>");
      out.print(title );
      out.write("</td>\n");
      out.write("\t                <td>");
      out.print(genere );
      out.write("</td>\n");
      out.write("\t            </tr>               \n");
      out.write("\n");
      out.write("\t            ");
      
	                }
	            
      out.write("\n");
      out.write("\n");
      out.write("\t        </tbody>\n");
      out.write("\t    </table>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("      /* NOTE: The styles were added inline because Prefixfree needs access to your styles and they must be inlined if they are on local disk! */\n");
      out.write("body, div, dl, dt, dd, ul, ol, li, h1, h2, h3, h4, h5, h6, pre, form, fieldset, input, textarea, p, blockquote, th, td { \n");
      out.write("  padding:0;\n");
      out.write("  margin:0;}\n");
      out.write("\n");
      out.write("body,\n");
      out.write("input,\n");
      out.write("textarea,\n");
      out.write("select {\n");
      out.write("  font-family: 'Open Sans', sans-serif;\n");
      out.write("  font-size: 16px;\n");
      out.write("  color: #4c4c4c;\n");
      out.write("}\n");
      out.write("\n");
      out.write("h1 {\n");
      out.write("  font-size: 32px;\n");
      out.write("  font-weight: 300;\n");
      out.write("  color: #4c4c4c;\n");
      out.write("  text-align: center;\n");
      out.write("  padding-top: 10px;\n");
      out.write("  margin-bottom: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".testbox1, .testbox2, .testbox3 {\n");
      out.write("  /*margin: 20px auto;*/\n");
      out.write("  width: 300px; \n");
      out.write("  /*height: 330px;*/ \n");
      out.write("  -webkit-border-radius: 8px/7px; \n");
      out.write("  -moz-border-radius: 8px/7px; \n");
      out.write("  border-radius: 8px/7px; \n");
      out.write("  background-color: #ebebeb; \n");
      out.write("  -webkit-box-shadow: 1px 2px 5px rgba(0,0,0,.31); \n");
      out.write("  -moz-box-shadow: 1px 2px 5px rgba(0,0,0,.31); \n");
      out.write("  box-shadow: 1px 2px 5px rgba(0,0,0,.31); \n");
      out.write("  border: solid 1px #cbc9c9;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".testbox1{\n");
      out.write("\theight: 330px; \n");
      out.write("}\n");
      out.write(".testbox2{\n");
      out.write("\theight: 290px; \n");
      out.write("}\n");
      out.write(".testbox3{\n");
      out.write("\theight: 185px; \n");
      out.write("}\n");
      out.write("form{\n");
      out.write("  margin: 0 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=text],input[type=password]{\n");
      out.write("  width: 200px; \n");
      out.write("  height: 39px; \n");
      out.write("  -webkit-border-radius: 0px 4px 4px 0px/5px 5px 4px 4px; \n");
      out.write("  -moz-border-radius: 0px 4px 4px 0px/0px 0px 4px 4px; \n");
      out.write("  border-radius: 0px 4px 4px 0px/5px 5px 4px 4px; \n");
      out.write("  background-color: #fff; \n");
      out.write("  -webkit-box-shadow: 1px 2px 5px rgba(0,0,0,.09); \n");
      out.write("  -moz-box-shadow: 1px 2px 5px rgba(0,0,0,.09); \n");
      out.write("  box-shadow: 1px 2px 5px rgba(0,0,0,.09); \n");
      out.write("  border: solid 1px #cbc9c9;\n");
      out.write("  margin-left: -5px;\n");
      out.write("  margin-top: 13px; \n");
      out.write("  padding-left: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=password]{\n");
      out.write("  margin-bottom: 25px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
